# ML Models

In [2]:
from sklearn.metrics import precision_score, recall_score

from Src.Data_Processing import (
    load_data,
    clean_data,
    feature_engineering,
    get_categorical_columns,
    encode_features
)

from Src.ML_Models import *

df = load_data("C:/Users/Admin/OneDrive/Documents/GitHub/Employee-Attrition-Analysis/Data/Raw/IBM HR Analysis.csv")
df = clean_data(df)
df = feature_engineering(df)

In [3]:
# Identifying categorical columns
categorical_cols = get_categorical_columns(df)

# Ensuring target variable is not encoded
categorical_cols = [col for col in categorical_cols if col != "Attrition"]

# One-hot encoding
df_encoded = encode_features(df, categorical_cols)


# Train / test split
X_train, X_test, y_train, y_test, feature_names = prepare_data(
    df_encoded,
    target_col="Attrition"
)

# Checking class distribution
print("Train distribution (%):")
print(y_train.value_counts(normalize=True) * 100)

print("\nTest distribution (%):")
print(y_test.value_counts(normalize=True) * 100)

Train distribution (%):
Attrition
0    83.867833
1    16.132167
Name: proportion, dtype: float64

Test distribution (%):
Attrition
0    83.900227
1    16.099773
Name: proportion, dtype: float64


## Training, Evaluating models

In [4]:
# Train
lr_model = train_logistic_regression(X_train, y_train)
dt_model = train_decision_tree(X_train, y_train)
rf_model = train_random_forest(X_train, y_train)


# Evaluate
evaluate(lr_model, X_train, X_test, y_train, y_test)
evaluate(dt_model, X_train, X_test, y_train, y_test)
evaluate(rf_model, X_train, X_test, y_train, y_test)


# Feature importance
show_feature_importance(lr_model, feature_names)
show_feature_importance(dt_model, feature_names)
show_feature_importance(rf_model, feature_names)

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(



LogisticRegression (TRAIN)
Confusion Matrix:
[[847  16]
 [ 85  81]]
Accuracy: 0.901846452866861
                    0           1  accuracy    macro avg  weighted avg
precision    0.908798    0.835052  0.901846     0.871925      0.896901
recall       0.981460    0.487952  0.901846     0.734706      0.901846
f1-score     0.943733    0.615970  0.901846     0.779851      0.890857
support    863.000000  166.000000  0.901846  1029.000000   1029.000000

LogisticRegression (TEST)
Confusion Matrix:
[[361   9]
 [ 41  30]]
Accuracy: 0.8866213151927438
                    0          1  accuracy   macro avg  weighted avg
precision    0.898010   0.769231  0.886621    0.833620      0.877277
recall       0.975676   0.422535  0.886621    0.699105      0.886621
f1-score     0.935233   0.545455  0.886621    0.740344      0.872480
support    370.000000  71.000000  0.886621  441.000000    441.000000

DecisionTreeClassifier (TRAIN)
Confusion Matrix:
[[863   0]
 [  0 166]]
Accuracy: 1.0
               0   

# Model comparison table

In [5]:
models = [lr_model, dt_model, rf_model]
model_names = ["Logistic Regression", "Decision Tree", "Random Forest"]

results = []

for model, name in zip(models, model_names):
    y_pred = model.predict(X_test)
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)
print("\n===== Model Comparison =====")
print(results_df)



===== Model Comparison =====
                 Model  Accuracy  Precision    Recall
0  Logistic Regression  0.886621   0.769231  0.422535
1        Decision Tree  0.750567   0.280899  0.352113
2        Random Forest  0.823129   0.360000  0.126761


# Interactive evaluation plots

In [6]:
plot_pr_curve_plotly(lr_model, X_test, y_test, "Logistic Regression")

In [7]:
plot_roc_curve_plotly(lr_model, X_test, y_test, "Logistic Regression")

In [30]:
plot_pr_curve_plotly(dt_model, X_test, y_test, "Decision Tree")

In [25]:
plot_roc_curve_plotly(dt_model, X_test, y_test, "Decision Tree")

In [26]:
plot_pr_curve_plotly(rf_model, X_test, y_test, "Random Forest")

In [27]:
plot_roc_curve_plotly(rf_model, X_test, y_test, "Random Forest")

In [8]:
results_df.to_csv("../reports/results/model_comparison.csv", index=False)